services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - app-for-learning-db

  app-for-learning-db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - prod-postgres-data:/var/lib/postgresql/data
    container_name: app-for-learning-db

volumes:
  prod-postgres-data:
